### ISSUE TITLE
Openframe device & X Windows?

### ISSUE THREAD

**Issue by jothebulb** [birdslikewires/openframe-linux#14]
Am I barking up the wrong tree when I try to run a project that uses X Windows, via this build on an OF1 (Joggler)? I'd like to use the Joggler to display an amateur radio clock display (800x480) called Ham Clock, which I can make & install in this build on my Joggler. However it doesn't display, and the diagnostics output says:
argv[0] = hamclock
HamClock version 2.60
Can not open X Windows display
If this is unachievable, I'll park this, but thank you for keeping the Jogglers going!

**Comment by jothebulb** [comment]
Just kept bashing away it, and with a few pointers from other radio amateurs, fixed it...
I was asking for advice at the Online Amateur Radio Community on Discord, a member was singing your praises as you had a given a talk for him at an Open Source conference a while back... Small world!
Thank you again for keeping the Joggler going.

**Comment by andydvsn** [comment]
That's fantastic you managed to get it sorted; I love keeping these things ticking over, always great to hear another one is being useful out there somewhere! :)
