### ISSUE TITLE
Kernel isn't included in versions lower then bionic.

### ISSUE THREAD

**Issue by RomSand** [birdslikewires/openframe-linux#2]
Tried to make trusty image it was created all files are there except the kernel. Thanks.

**Comment by andydvsn** [comment]
Wow, I can't believe I've not seen this issue until now. Is there a reason you were needing Trusty and not Bionic?

**Comment by RomSand** [comment]
Hi, I could install EMGD under bionic(using older 4.4 kernel). I needed trusty to be able to compile driver for kernel under Bionic in fails compilation...

**Comment by andydvsn** [comment]
Righto, I'll try to debug a trusty build with of-imgcreate in the next few days.

**Comment by sandmix** [comment]
Thanks, but I already used old kernel so no need for me.

Thank you.
